In [5]:
from pathlib import Path
import pandas as pd
import re
from datetime import datetime

basic_info = {}

with open('../data/sample/CME/SPX_040125/May2025.csv', 'r') as file:
    file.readline()
    line2 = file.readline().strip()
    line3 = file.readline().strip()
    
pattern2 = r'(.*?),\s*Last:\s*(.*?),\s*Change:\s*(-?\d+\.?\d*)'
pattern3 = r'"Date:(.*?)",Bid:(.*?),Ask:(.*?),Size:(.*?),Volume:(.*?)'

matches2 = re.match(pattern2, line2)
matches3 = re.match(pattern3, line3)
basic_info['underlying'] = matches2.group(1).strip()
basic_info['underlying_last'] = float(matches2.group(2).strip())
basic_info['underlying_change'] = float(matches2.group(3).strip())
basic_info['Date'] = datetime.strptime(matches3.group(1).strip(), '%B %d, %Y at %I:%M %p EDT')
basic_info['Bid'] = float(matches3.group(2).strip())
basic_info['Ask'] = float(matches3.group(3).strip())
basic_info['Size'] = matches3.group(4).strip()
basic_info['Volume'] = 0 if matches3.group(5).strip() == '' else int(matches3.group(5).strip())

path = "../data/sample/CME/SPX_040125/Apr2025.csv"
df = pd.read_csv(path, skiprows=3)
T = df.iloc[:, 0]
K = df.iloc[:, 11]
cols = ['ticker', 'last', 'net', 'bid', 'ask', 'volume', 'IV', 'Delta', 'Gamma', 'open']
call = df.iloc[:, 1:11]
call.columns = cols
call['refdate'] = basic_info['Date']
call['S'] = basic_info['underlying_last']
call['T'] = T
call['K'] = K
put = df.iloc[:, 12:]
put.columns = cols
display(call)
display(put)

,ticker,last,net,bid,ask,volume,IV,Delta,Gamma,open,refdate,S,T,K
0,SPXW250401C02400000,3299.07,0.0,3193.1,3193.70,0,0.0000,1.0000,0.0,1,2025-04-01 14:37:00,5593.04,Tue Apr 01 2025,2400.0
1,SPXW250401C02600000,0.00,0.0,2993.0,2993.70,0,0.0000,1.0000,0.0,0,2025-04-01 14:37:00,5593.04,Tue Apr 01 2025,2600.0
2,SPXW250401C02800000,0.00,0.0,2793.1,2793.70,0,0.0000,0.9999,0.0,0,2025-04-01 14:37:00,5593.04,Tue Apr 01 2025,2800.0
3,SPXW250401C03000000,0.00,0.0,2593.1,2593.70,0,0.0000,0.9999,0.0,0,2025-04-01 14:37:00,5593.04,Tue Apr 01 2025,3000.0
4,SPXW250401C03200000,0.00,0.0,2393.1,2393.70,0,0.0000,0.9999,0.0,0,2025-04-01 14:37:00,5593.04,Tue Apr 01 2025,3200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4392,SPXW250430C07400000,0.05,0.0,0.0,0.15,0,0.3013,0.0002,0.0,753,2025-04-01 14:37:00,5593.04,Wed Apr 30 2025,7400.0
4393,SPXW250430C07500000,0.05,0.0,0.0,0.10,0,0.3056,0.0002,0.0,113,2025-04-01 14:37:00,5593.04,Wed Apr 30 2025,7500.0
4394,SPXW250430C07600000,0.35,0.0,0.0,0.10,0,0.3184,0.0002,0.0,1,2025-04-01 14:37:00,5593.04,Wed Apr 30 2025,7600.0
4395,SPXW250430C07800000,0.05,0.0,0.0,0.10,0,0.3434,0.0001,0.0,128,2025-04-01 14:37:00,5593.04,Wed Apr 30 2025,7800.0
4396,SPXW250430C08000000,0.05,0.0,0.0,0.10,0,0.3678,0.0001,0.0,586,2025-04-01 14:37:00,5593.04,Wed Apr 30 2025,8000.0

,ticker,last,net,bid,ask,volume,IV,Delta,Gamma,open
0,SPXW250401P02400000,0.03,0.005,0.0,0.05,2,0.0,0.0000,0.0,74
1,SPXW250401P02600000,0.05,0.000,0.0,0.05,0,0.0,0.0000,0.0,18
2,SPXW250401P02800000,0.05,0.000,0.0,0.05,0,0.0,-0.0001,0.0,10
3,SPXW250401P03000000,0.10,0.000,0.0,0.05,0,0.0,-0.0001,0.0,84
4,SPXW250401P03200000,0.15,0.000,0.0,0.05,0,0.0,-0.0001,0.0,101
...,...,...,...,...,...,...,...,...,...,...
4392,SPXW250430P07400000,0.00,0.000,1772.7,1790.50,0,0.0,-0.9998,0.0,0
4393,SPXW250430P07500000,0.00,0.000,1872.3,1889.40,0,0.0,-0.9999,0.0,0
4394,SPXW250430P07600000,0.00,0.000,1972.0,1989.50,0,0.0,-0.9999,0.0,0
4395,SPXW250430P07800000,0.00,0.000,2172.2,2187.80,0,0.0,-1.0000,0.0,1
4396,SPXW250430P08000000,1900.89,0.000,2370.5,2388.60,0,0.0,-1.0000,0.0,41

In [2]:
line

첫 번째 줄: ['SP 500 INDEX', 'Last: 5593.04', 'Change:  -18.81']
두 번째 줄: ['"Date: April 1', ' 2025 at 2:37 PM EDT"', 'Bid: 5591.5298', 'Ask: 5594.7798', 'Size: 1*1', 'Volume: 0']

In [56]:

basic_info


# data_dict = {
#         'Date': matches.group(1).split(": ", 1)[1],
#         'Bid': matches.group(2).split(": ", 1)[1],
#         'Ask': matches.group(3).split(": ", 1)[1],
#         'Size': matches.group(4).split(": ", 1)[1],
#         'Volume': matches.group(5).split(": ", 1)[1]
#     }

{'underlying': 'SP 500 INDEX',
 'underlying_last': 5593.04,
 'underlying_change': -18.81,
 'Date': datetime.datetime(2025, 4, 1, 14, 37),
 'Bid': 5591.5298,
 'Ask': 5594.7798,
 'Size': '1*1',
 'Volume': 0}

In [54]:
float('')

ValueError: could not convert string to float: ''

In [49]:
import re
from datetime import datetime

# 주어진 문자열 예시
text = "SP 500 INDEX,Last: 5593.04,Change: 18.81,Date: April 1, 2025 at 2:37 PM EDT,Bid: 5591.5298,Ask: 5594.7798,Size: 1*1,Volume: 0"

# 정규 표현식 패턴
pattern2 = r'(.*?),\s*Last:\s*(.*?),\s*Change:\s*(-?\d+\.?\d*),\s*Date:\s*(.*?),\s*Bid:\s*(.*?),\s*Ask:\s*(.*?),\s*Size:\s*(.*?),\s*Volume:\s*(.*)'

# 정규 표현식으로 매칭
match = re.match(pattern2, text)

if match:
    result = {
        'underlying': match.group(1),
        'underlying_last': match.group(2),
        'underlying_change': match.group(3),  # Change 값을 제대로 추출
        'Date': datetime.strptime(match.group(4), '%B %d, %Y at %I:%M %p EDT'),
        'Bid': match.group(5),
        'Ask': match.group(6),
        'Size': match.group(7),
        'Volume': match.group(8)
    }
    print(result)
else:
    print("정규 표현식 매칭 실패")

{'underlying': 'SP 500 INDEX', 'underlying_last': '5593.04', 'underlying_change': '18.81', 'Date': datetime.datetime(2025, 4, 1, 14, 37), 'Bid': '5591.5298', 'Ask': '5594.7798', 'Size': '1*1', 'Volume': '0'}